# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.define :server do |srv|
    srv.vm.hostname = "ext-serv"
    srv.vm.network "private_network", ip: "192.168.33.10", :mac => "080027538b38", virtualbox__intnet: "externnet"
    srv.vm.provision "shell", path: "server.sh"
    config.ssh.forward_x11 = true
  end

  config.vm.define :nat do |nat|
    nat.vm.hostname = "nat"
    nat.vm.network "private_network", ip: "192.168.33.2", :mac => "080027004471", virtualbox__intnet: "externnet"
    nat.vm.network "private_network", ip: "192.168.40.2", :mac => "080027004472", virtualbox__intnet: "internnet"
    nat.vm.synced_folder "./src", "/nat"
    nat.vm.provision "shell", path: "nat.sh"
    config.ssh.forward_x11 = true
    nat.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

  config.vm.define :client do |cl|
    cl.vm.hostname = "int-clnt"
    cl.vm.network "private_network", ip: "192.168.40.5", :mac => "080027c11347", virtualbox__intnet: "internnet"
    cl.vm.provision "shell", path: "client.sh"
    config.ssh.forward_x11 = true
  end

end
